### PR TITLE
[Refactor] Map enum string keys to array to simplify glue code

### PR DESCRIPTION
**Pull request by 9oelM**
This PR just introduces a small change. Instead of writing instruction keys like:

```ts
const ImageSmoothingQualityValues = ["low", "medium", "high"];
```
Now all you have to do is

```ts
const ImageSmoothingQualityValues = enumKeysToArray(ImageSmoothingQuality);
```

This way, we can prevent errors better.

- [x] Add a test suite
- [x] Refactor

### CODE REVIEW

**Comment by jtenner** [comment]
One of the important things about `as2d` is the way the web assembly context communicates with the JavaScript wrapper. It attempts to reduce the number of external calls out into JavaScript because there is a small amount of overhead (that adds up over time.)

The web assembly side emulates what the canvas context does on the JavaScript side, then sends up an optimized set of remote procedure calls to an interpreter which then calls functions like `ctx.setTransform()` instead of `ctx.scale()` and `ctx.rotate()`.

This works by sending up `enum` values instead of strings, and the interpreter uses optimized Array access to ensure that this works.

Using `Object.values(enum)` according to the JavaScript specification like this means that we cannot rely on the order the properties exist in that specific array. It's currently the case that the properties *do* work correctly, but that is happenstance. This is the *fastest* and *clearest* solution I could come up with to ensure speed and efficiency for the external `commit` glue code function.

I have to respectfully decline this refactor, even though it looks like, on the surface level, that it would be useful.

**Comment by 9oelM** [comment]
@jtenner now I start to understand the reasons behind the codes you've written. But it's a good learning opportunity. Thanks. I'm closing this PR!

**Comment by jtenner** [comment]
I actually would love some help in regards to a potential optimization involving a complete rewrite of the algorithm. Is that something you might be interested in helping me with?

**Comment by 9oelM** [comment]
@jtenner sorry I just have seen this. I would be glad to do that. But FYI I'm kind of new to this AssemblyScript and low level programming world (especially specific in Typescript, which makes it more special), I doubt if I can help really much. But I would love to learn and get things going.

**Pull request closed without merging**
